<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?= (isset($title) ? ($title . ' &mdash; ' . $this->site('title')) : $this->site('title')); ?></title>
    <meta title="description" content="<?= (isset($description) ? $description : $this->site('description')); ?>">
    <link type="text/css" rel="stylesheet" href="<?= $this->asset('css/main.css') ?>" />
    <link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Mono" rel="stylesheet">
    <link type="image/x-icon" rel="icon" href="<?= $this->url('img/favicon.ico') ?>"/>
    <meta title="author" content="<?= (isset($author) ? $author : $this->site('author')); ?>>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="generator" content="tapestry"/>
</head>
<body class="text-center">

<header class="main">
    <div class="max-width-4 mx-auto flex">
        <div class="flex-auto">
            <div class="brand flex-none">
                <h1 class="caps"><a href="<?= $this->url() ?>">Tapestry</a></h1>
                <small>Build static sites with PHP Plates</small>
            </div>
        </div>
        <nav class="flex items-center right">
            <ul class="list-reset list-inline m0">
                <li class="m0"><a href="https://github.com/tapestry-cloud/tapestry/releases" class="btn btn-link">Download</a></li>
                <li class="m0"><a href="<?= $this->url('documentation') ?>" class="btn btn-outline">Documentation</a></li>
            </ul>
        </nav>
    </div>

    <div class="max-width-4 mx-auto">
        <div class="center fit" style="margin-top: 3rem;margin-bottom: 6rem;">
            <h1 style="font-weight: lighter;">It's <em>another</em> Static Site Generator&hellip;</h1>
            <h3 style="font-weight: lighter;">&hellip; except this one uses the PHP Plates template system!</h3>
        </div>
    </div>
</header>

<main class="max-width-4 mx-auto px3">
    <?= $this->section('content') ?>
</main>

<footer class="main py3">
    <p class="center">
        &copy; <?= date('Y') ?> Simon Dann, Tapestry is licensed under the <a href="https://github.com/tapestry-cloud/tapestry/blob/master/LICENSE" target="_blank">MIT License.</a>
    </p>
    <p class="center">
        See an error or would like to contribute to this documentation? The source is <a href="https://github.com/tapestry-cloud/tapestry-cloud-src" target="_blank">available over on github</a>.
    </p>
</footer>
<script src="<?= $this->asset('js/all.js') ?>" type="application/javascript"></script>
</body>
</html>