<!DOCTYPE html>
<html lang="en-GB">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title><?= (isset($title) ? ($title . ' &mdash; ' . $this->site('title')) : $this->site('title')); ?></title>

    <meta name="author" content="<?= (isset($author) ? $author : $this->site('author')); ?>>">
    <meta name="description" content="<?= trim(preg_replace('/\s+/', ' ',(isset($description) ? $description : $this->getExcerpt(160)))) ?>" />

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="generator" content="tapestry.cloud"/>
    <link rel="canonical" href="<?= $this->getUrl() ?>" />

    <link rel="shortcut icon" type="image/x-icon" href="<?= $this->url('img/favicon.ico') ?>"/>

    <!-- Rich Link Preview -->
    <meta property="og:title" content="<?= (isset($title) ? ($title . ' &mdash; ' . $this->site('title')) : $this->site('title')); ?>" />
    <meta property="og:description" content="<?= trim(preg_replace('/\s+/', ' ',(isset($description) ? $description : $this->getExcerpt(160)))) ?>" />
    <meta property="og:image" content="<?= $this->url('img/twitter-card.png') ?>" />
    <meta property="og:url" content="<?= $this->getUrl() ?>" />
    <!-- ./ rich link preview -->

    <!-- Twitter Card -->
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="<?= $this->site('twitter-card.site') ?>" />
    <meta name="twitter:creator" content="<?= $this->site('twitter-card.creator') ?>" />
    <meta name="twitter:title" content="<?= (isset($title) ? ($title . ' &mdash; ' . $this->site('title')) : $this->site('title')); ?>" />
    <meta name="twitter:description" content="<?= trim(preg_replace('/\s+/', ' ',(isset($description) ? $description : $this->getExcerpt(160)))) ?>" />
    <meta name="twitter:image" content="<?= $this->url('img/twitter-card.png') ?>" />
    <!-- ./ twitter card -->

    <link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Mono" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="<?= $this->asset('css/main-min.css') ?>"/>
</head>
<body>
<header>
    <section class="nav-bar">
        <div class="content max-width-4 mx-auto flex">
            <div class="logo flex-auto items-center left">
                <a href="<?= $this->url() ?>" title="Tapestry">
                    <img src="<?= $this->url('img/logo.png') ?>" alt="Tapestry" title="Tapestry"/>
                </a>
            </div>
            <nav class="flex items-center right">
                <ul class="list-reset list-inline m0">
                    <li class="m0"><a href="<?= $this->url('documentation') ?>" class="btn btn-link">Documentation</a></li>
                    <li class="m0"><a href="https://github.com/tapestry-cloud/tapestry/releases" class="btn brand">Download</a></li>
                </ul>
            </nav>
        </div>
    </section>
    <?php if ($breadcrumbs = $this->site('documentation-menu-breadcrumb-lookup.'. base64_encode($this->getUrl()), null)) { ?>
    <section class="breadcrumbs overflow-auto">
        <div class="max-width-4 mx-auto">
            <ul class="small">
                <?php foreach ($breadcrumbs as $breadcrumb){ ?>
                <li><?= $breadcrumb ?></li>
                <?php } ?>
            </ul>
        </div>
    </section>
    <?php } ?>
</header>

<a href="https://github.com/tapestry-cloud/tapestry" class="github-corner" aria-label="View source on Github">
    <svg width="80" height="80" viewBox="0 0 250 250" aria-hidden="true">
        <path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path>
        <path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2"
              fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path>
        <path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z"
              fill="currentColor" class="octo-body"></path>
    </svg>
</a>

<main class="max-width-4 mx-auto mb3">
    <a name="top"></a>
    <div class="clearfix">
        <section class="documentation-menu col py3 xs-col-12 sm-col-4 col-4 pr2">
            <div class="nav">
                <?php
                    $menuItems = $this->site('documentation-menu');
                    if (count($menuItems) > 0 ) {
                        $this->insert('documentation/_partials/navigation', ['menuItems' => $menuItems, 'currentUrl' => $this->getUrl()]);
                    }
                ?>
            </div>
        </section>
        <article class="documentation col xs-col-12 sm-col-8 col-8 p3"><?= $this->section('content') ?></article>
    </div>
</main>

<footer class="py3">
    <div style="padding: 0 3rem;">
        <p class="center">
            &copy; <?= date('Y') ?> <a href="https://www.photogabble.co.uk/?utm_source=tapestry&utm_medium=referral&utm_campaign=footer_author_link" target="_blank">Simon Dann</a>, Tapestry is licensed under the <a href="https://github.com/tapestry-cloud/tapestry/blob/master/LICENSE" target="_blank">MIT License.</a>
        </p>
        <p class="center">
            See an error or would like to contribute to this documentation? The source is <a href="https://github.com/tapestry-cloud/tapestry-cloud-src" target="_blank">available over on github</a>.
        </p>
    </div>
</footer>

<?php if ($this->site('google-analytics')) { ?>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', '<?= $this->site('google-analytics') ?>', 'auto');
        ga('send', 'pageview');
    </script>
    <!-- Twitter universal website tag code -->
    <script>
        !function(e,t,n,s,u,a){e.twq||(s=e.twq=function(){s.exe?s.exe.apply(s,arguments):s.queue.push(arguments);
        },s.version='1.1',s.queue=[],u=t.createElement(n),u.async=!0,u.src='//static.ads-twitter.com/uwt.js',
            a=t.getElementsByTagName(n)[0],a.parentNode.insertBefore(u,a))}(window,document,'script');
        // Insert Twitter Pixel ID and Standard Event data below
        twq('init','nxk9f');
        twq('track','PageView');
    </script>
    <!-- End Twitter universal website tag code -->
<?php } ?>
<script src="<?= $this->asset('js/all.js') ?>" type="application/javascript"></script>
</body>
</html>