<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?= (isset($title) ? ($title . ' &mdash; ' . $this->site('title')) : $this->site('title')); ?></title>
    <meta title="description" content="<?= (isset($description) ? $description : $this->site('description')); ?>">
    <link type="text/css" rel="stylesheet" href="<?= $this->asset('css/main-min.css') ?>"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Mono" rel="stylesheet">
    <link type="image/x-icon" rel="icon" href="<?= $this->url('img/favicon.ico') ?>"/>
    <meta title="author" content="<?= (isset($author) ? $author : $this->site('author')); ?>>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="generator" content="tapestry"/>
</head>
<body>

<header>
    <section class="nav-bar">
        <div class="max-width-4 mx-auto flex" style="height: 100%;">
            <div class="flex-auto items-center left">
                <a href="<?= $this->url() ?>" title="Tapestry">
                    <img src="<?= $this->url('img/logo.png') ?>" alt="Tapestry" title="Tapestry"/>
                </a>
            </div>
            <nav class="flex items-center right">
                <ul class="list-reset list-inline m0">
                    <li class="m0"><a href="<?= $this->url('documentation') ?>" class="btn btn-link">Documentation</a></li>
                    <li class="m0"><a href="https://github.com/tapestry-cloud/tapestry/releases" class="btn brand">Download</a></li>
                </ul>
            </nav>
        </div>
    </section>
    <?php if ($breadcrumbs = $this->site('documentation-menu-breadcrumb-lookup.'. $this->getUrl(), null)) { ?>
    <section class="breadcrumbs overflow-auto">
        <div class="max-width-4 mx-auto">
            <ul class="small">
                <?php foreach ($breadcrumbs as $breadcrumb){ ?>
                <li><?= $breadcrumb ?></li>
                <?php } ?>
            </ul>
        </div>
    </section>
    <?php } ?>
</header>

<main class="max-width-4 mx-auto mb3">
    <a name="top"></a>
    <div class="clearfix">
        <section class="documentation-menu col py3 col-4 pr2">
            <div class="nav">
                <?php
                    $menuItems = $this->site('documentation-menu');
                    if (count($menuItems) > 0 ) {
                        $this->insert('documentation/_partials/navigation', ['menuItems' => $menuItems, 'currentUrl' => $this->getUrl()]);
                    }
                ?>
            </div>
        </section>
        <article class="documentation col col-8 py3 pl3"><?= $this->section('content') ?></article>
    </div>
</main>

<footer class="py3">
    <p class="center">
        &copy; <?= date('Y') ?> Simon Dann, Tapestry is licensed under the <a href="https://github.com/tapestry-cloud/tapestry/blob/master/LICENSE" target="_blank">MIT License.</a>
    </p>
    <p class="center">
        See an error or would like to contribute to this documentation? The source is <a href="https://github.com/tapestry-cloud/tapestry-cloud-src" target="_blank">available over on github</a>.
    </p>
</footer>

<?php if ($this->site('google-analytics')) { ?>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', '<?= $this->site('google-analytics') ?>', 'auto');
        ga('send', 'pageview');
    </script>
<?php } ?>
<script src="<?= $this->asset('js/all.js') ?>" type="application/javascript"></script>
</body>
</html>