<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?= (isset($title) ? ($title . ' &mdash; ' . $this->site('title')) : $this->site('title')); ?></title>
    <meta title="description" content="<?= (isset($description) ? $description : $this->site('description')); ?>">
    <link type="text/css" rel="stylesheet" href="<?= $this->url('css/main.css') ?>" />
    <link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Mono" rel="stylesheet">
    <link type="image/x-icon" rel="icon" href="<?= $this->url('img/favicon.ico') ?>"/>
    <meta title="author" content="<?= (isset($author) ? $author : $this->site('author')); ?>>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="generator" content="tapestry"/>
</head>
<body class="text-center">

<header class="flex">
    <div>
        <h1 class="caps">Tapestry</h1>
        <h2>Build static sites with PHP Plates</h2>
    </div>
    <nav>
        <a href="#" class="btn btn-outline">Documentation</a>
        <a href="#" class="btn btn-outline">Download</a>
    </nav>
</header>

<main class="max-width-4 mx-auto px3">
    <div class="mt4 clearfix">
        <section class="col col-4 pr2">
            <div class="nav">
                <ul>
                    <li>
                        <span>Getting Started</span>
                        <ul>
                            <li><a href="<?= $this->url('documentation') ?>">Quickstart Guide</a></li>
                            <li><a href="<?= $this->url('documentation/configuration') ?>">Configuration</a></li>
                            <li><a href="<?= $this->url('documentation/directory-structure') ?>">Project Directory Structure</a></li>
                        </ul>
                    </li>
                    <li>
                        <span>Core Concepts</span>
                        <ul>
                            <li><a href="<?= $this->url('documentation/commands') ?>">Commands</a></li>
                            <li><a href="<?= $this->url('documentation/kernel') ?>">Project Kernel</a></li>
                            <li><a href="<?= $this->url('documentation/content-types') ?>">Content Types</a></li>
                            <li><a href="<?= $this->url('documentation/taxonomy') ?>">Taxonomy</a></li>
                        </ul>
                    </li>
                    <li>
                        <span>Templates</span>
                        <ul>
                            <li><a href="<?= $this->url('documentation/php-plates') ?>">PHP Plates</a></li>
                            <li><a href="<?= $this->url('documentation/helpers') ?>">Helpers</a></li>
                        </ul>
                    </li>
                    <li>
                        <span>Extending Tapestry</span>
                        <ul>
                            <li><a href="<?= $this->url('documentation/steps') ?>">Steps</a></li>
                            <li><a href="<?= $this->url('documentation/container') ?>">Container</a></li>
                            <li><a href="<?= $this->url('documentation/project') ?>">Project</a></li>
                            <li><a href="<?= $this->url('documentation/events') ?>">Events</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </section>
        <article class="col col-8 pl2"><?= $this->section('content') ?></article>
    </div>
</main>
</body>
</html>