---
layout: documentation
title: Assets
---

<h2>Assets</h2>

<ul>
    <li><a href="#assets">Assets</a>
        <ul>
            <li><a href="#assets-folder-structure">_assets folder structure</a></li>
            <li><a href="#gulp">Gulp</a></li>
            <li><a href="#static-assets">Static Assets</a></li>
        </ul>
    </li>
</ul>


<h3><a name="assets" href="#assets">Assets</a></h3>

<p>
    <strong>@todo</strong> describe the _assets folder structure and how it is built with the provided gulp tasks; include
    description about other static assets and how they may be copied into the build directory (still not sure if Tapestry
    should provide a copy facility on top of ignore, or just ignore and have the task runner do the final copy).
</p>

<h4><a name="assets-folder-structure" href="#assets-folder-structure">_assets folder structure</a></h4>

<h4><a name="gulp" href="#gulp">Gulp</a></h4>

<h4><a name="static-assets" href="#static-assets">Static Assets</a></h4>
