---
layout: documentation
title: Collections
---

<h2>Collections</h2>

<ul>
    <li><a href="#collections">Collections</a>
        <ul>
            <li><a href="#request-collections">How to request collections</a></li>
            <li><a href="#pagination">Pagination</a></li>
        </ul>
    </li>
</ul>

<h3><a name="collections" href="#collections">Collections</a></h3>

<p>
    <strong>@todo</strong> describe what collections are and how to use them within your templates. Link to front matter, content types
    and content generators for additional reading
</p>

<h4><a name="request-collections" href="#request-collections">How to request collections</a></h4>

<h4><a name="pagination" href="#pagination">Pagination</a></h4>

