---
layout: documentation
title: Commands
---

<h2>Commands</h2>

<ul>
    <li>
        <a href="#commands">Commands</a>
        <ul>
            <li>
                <a href="#build-command">Build current Project Workspace</a>
            </li>
            <li>
                <a href="#init-command">Initiate New Project Workspace</a>
            </li>
            <li>
                <a href="#self-update-command">Self Update</a>
            </li>
        </ul>
    </li>
    <li>
        <a href="#extending-commands">Adding your own Commands</a>
    </li>
</ul>

<h3><a name="commands" href="#commands">Commands</a></h3>

<h4><a name="build-command" href="#build-command">Build current Project Workspace</a></h4>

<h4><a name="init-command" href="#init-command">Initiate New Project Workspace</a></h4>

<h4><a name="self-update-command" href="#self-update-command">Self Update</a></h4>

<h3><a name="extending-commands" href="#extending-commands">Adding your own Commands</a></h3>