---
layout: documentation
title: Configuration
---

<h2>Configuration</h2>

<ul>
    <li>
        <a href="#configuration">Configuration</a>
        <ul>
            <li>
                <a href="#env-configuration">Environment Configuration</a>
            </li>
        </ul>
    </li>
</ul>

<h3><a name="configuration" href="#configuration">Configuration</a></h3>

<p>
    Configuration for Tapestry is stored in either PHP or YAML format within the root of your project workspace. By default
    Tapestry initiates a new project workspace with a <code>config.php</code>, however you can replace that with <code>config.yaml</code> if
    you wish to use YAML to configure Tapestry.
</p>

<aside class="notice">
    <p>
        You may only have either a <code>config.php</code> or a <code>config.yaml</code> file in your project; Tapestry will exit with
        an error if both exist.
    </p>
</aside>

<h4><a name="env-configuration" href="#env-configuration">Environment Configuration</a></h4>

<p>
    
</p>



