---
layout: documentation
title: Content Renderers
---

<h2>Content Renderers</h2>

<ul>
    <li><a href="#content-renderers">Content Renderers</a>
        <ul>
            <li><a href="#the-markdown-renderer">The Markdown Renderer</a></li>
            <li><a href="#the-plates-renderer">The Plates Renderer</a></li>
            <li><a href="#the-html-renderer">The HTML Renderer</a></li>
            <li><a href="#the-default-renderer">The Default Renderer</a></li>
        </ul>
    </li>
</ul>

<hr/>

<h3><a name="content-renderers" href="#content-renderers">Content Renderers</a></h3>
<p>
    Content Renderers in Tapestry are classes that operate on file types. Every file that is parsed by Tapestry has a
    renderer class matched to it by file type during the
    <a href="<?= $this->url('documentation/steps') ?>#load-source-files">LoadSourceFiles</a> step.
</p>
<h4><a name="the-markdown-renderer" href="#the-markdown-renderer">The Markdown Renderer</a></h4>
<p>
    The <a href="https://github.com/tapestry-cloud/tapestry/blob/master/src/Entities/Renderers/MarkdownRenderer.php">Markdown Renderer</a>
    operates on any file with an extension of <em>md</em> or <em>markdown</em>. It uses the markdown extra functionality of the
    <a href="https://github.com/michelf/php-markdown">michelf/php-markdown</a> library to parse markdown into html.
</p>
<h4><a name="the-plates-renderer" href="#the-plates-renderer">The Plates Renderer</a></h4>
<p>
    The <a href="https://github.com/tapestry-cloud/tapestry/blob/master/src/Entities/Renderers/PlatesRenderer.php">Plates Renderer</a>
    operates on any file with an extension of <em>php</em> or <em>phtml</em>. It uses the Tapestry extension of the
    <a href="http://platesphp.com/">Plates</a> template system to parse the files into html.

</p>
<h4><a name="the-html-renderer" href="#the-html-renderer">The HTML Renderer</a></h4>
<p>
    The <a href="https://github.com/tapestry-cloud/tapestry/blob/master/src/Entities/Renderers/HTMLRenderer.php">HTML Renderer</a>
    operates on any file with an extension of <em>htm</em> or <em>html</em>. This renderer was created to allow htm and html files
    to have Front Matter. If a file has a template defined in its Front Matter then this renderer will mutate it into a phtml
    file to be further rendered by the plates renderer.
</p>
<h4><a name="the-default-renderer" href="#the-default-renderer">The Default Renderer</a></h4>
<p>
    Any input file that does not have an extension matching any other renderer will have the
    <a href="https://github.com/tapestry-cloud/tapestry/blob/master/src/Entities/Renderers/DefaultRenderer.php">Default Renderer</a>
    assigned to it. This renderer mutates files attached to it, marking them to be copied and not compiled.
</p>