---
layout: documentation
title: Content Types
---

<h2>Content Types</h2>

<ul>
    <li><a href="#content-types">Content Types</a>
        <ul>
            <li><a href="#the-default-content-type">The default blog content type</a></li>
            <li><a href="#defining-your-own-content-types">Defining your own content types</a></li>
        </ul>
    </li>
</ul>

<hr/>

<h3><a name="content-types" href="#content-types">Content Types</a></h3>
<p>&hellip;</p>
<h4><a name="the-default-content-type" href="#the-default-content-type">The default blog content type</a></h4>
<p>&hellip;</p>
<h4><a name="defining-your-own-content-types" href="#defining-your-own-content-types">Defining your own content types</a></h4>
<p>&hellip;</p>
