---
layout: documentation
title: Content Renderers
---

<h2>Content Renderers</h2>

<ul>
    <li><a href="#content-renderers">Content Renderers</a>
        <ul>
            <li><a href="#the-markdown-renderer">The Markdown Renderer</a></li>
            <li><a href="#the-plates-renderer">The Plates Renderer</a></li>
            <li><a href="#the-html-renderer">The HTML Renderer</a></li>
            <li><a href="#the-default-renderer">The Default Renderer</a></li>
        </ul>
    </li>
</ul>

<hr/>

<h3><a name="content-renderers" href="#content-renderers">Content Renderers</a></h3>
<p>&hellip;</p>
<h4><a name="the-markdown-renderer" href="#the-markdown-renderer">The Markdown Renderer</a></h4>
<p>&hellip;</p>
<h4><a name="the-plates-renderer" href="#the-plates-renderer">The Plates Renderer</a></h4>
<p>&hellip;</p>
<h4><a name="the-html-renderer" href="#the-html-renderer">The HTML Renderer</a></h4>
<p>&hellip;</p>
<h4><a name="the-default-renderer" href="#the-default-renderer">The Default Renderer</a></h4>
<p>&hellip;</p>