---
layout: documentation
title: Project Directory Structure
---

<h2>Project Directory Structure</h2>

<ul>
    <li><a href="#project-directory-structure">Project Directory Structure</a></li>
</ul>

<h3><a name="project-directory-structure" href="#project-directory-structure">Project Directory Structure</a></h3>

<pre class="language-treeview">
<code>webroot/
├── source/
|   ├── _assets/
|   |   ├── img
|   |   ├── js
|   |   └── less
|   ├── _blog/
|   |   └── 2016-01-01-hello-world.md
|   ├── _templates/
|   |   └── default.phtml
|   ├── _views/
|   |   └── blog.phtml
|   └── index.phtml
├── .gitignore
├── config.php
├── gulpfile.js
├── kernel.php
└── package.json</code>
</pre>

<h4><a name="xxx" href="#xxx">xxx</a></h4>