---
layout: documentation
title: Quickstart Guide
---

<h2>Quickstart Guide</h2>

<ul>
    <li><a href="#installation">Installation</a>
        <ul>
            <li><a href="#system-requirements">System Requirements</a></li>
            <li><a href="#installing-tapestry">Installing Tapestry</a></li>
            <li><a href="#configuration">Configuration</a></li>
        </ul>
    </li>

</ul>

<h3><a name="installation" href="#installation">Installation</a></h3>

<h4><a name="system-requirements" href="#system-requirements">System Requirements</a></h4>

<p>
    Tapestry has few system requirements, designed for simplicity it only requires that you have <code>PHP >= 5.6.4</code> installed.
</p>

<h4><a name="installing-tapestry" href="#installing-tapestry">Installing Tapestry</a></h4>

<p>
    For simplicity Tapestry is distributed as a compiled <code>.phar</code> archive available from the github repositories
    releases page <a href="https://github.com/carbontwelve/tapestry/releases">here</a>. Upon downloading the zip file place
    its contents into a folder and then add that folders path to your users <code>%PATH%</code>. On windows this is done through
    clicking <em>Change my environment variables</em> within the <em>Control Panel\All Control Panel Items\User Accounts</em>
    control panel pane.

</p>

<h4><a name="configuration" href="#configuration">Configuration</a></h4>
