---
layout: documentation
title: Quickstart Guide
---

<h2>Quickstart Guide</h2>

<ul>
    <li><a href="#welcome">Welcome</a>
        <ul>
            <li><a href="#installing-tapestry">Installing Tapestry</a></li>
            <li><a href="#first-website">Scaffold your first website</a></li>
            <li><a href="#project-structure">Project Structure</a></li>
        </ul>
    </li>
    <li>
        <a href="#building-and-previewing">Building &amp; Previewing</a>
        <ul>
            <li>
                <a href="#preview-php">Preview with PHP</a>
            </li>
            <li>
                <a href="#preview-gulp">Preview with Gulp Task</a>
            </li>
        </ul>
    </li>
</ul>

<hr/>

<h3><a name="welcome" href="#welcome">Welcome</a></h3>

<p>
    This documentation aims to be a comprehensive guide to Tapestry; here we'll cover topics such as
    <a href="<?= $this->url('documentation/installation')?>">Installing Tapestry</a>,
    <a href="<?= $this->url('documentation/start-new-website') ?>">starting your first website</a> and
    <a href="<?= $this->url('documentation/deploying') ?>">Deploying</a>.
</p>

<h4><a name="installing-tapestry" href="#installing-tapestry">Installing Tapestry</a></h4>

<p>
    There are <a href="<?= $this->url('documentation/installation') ?>">multiple methods</a> of installing Tapestry, the
    quickest is installing globally via Composer:
</p>

<pre class="language-bash"><code>$ composer global require tapestry-cloud/tapestry</code></pre>

<p>
    To test that you have successfully installed Tapestry you can run <code>tapestry --version</code> in your terminal and
    you should see <code>Tapestry version <?= \Tapestry\Tapestry::VERSION ?>, environment local</code> in return.
</p>

<aside class="notice blue">
    <p>
        If you prefer not to install via composer, you can download Tapestry as a .phar
        <a href="https://github.com/tapestry-cloud/tapestry/releases" target="_blank">here</a>.
    </p>
</aside>

<h4><a name="first-website" href="#first-website">Scaffold your first website</a></h4>

<p>
    Tapestry comes with a basic project scaffold built in, if you have Tapestry installed globally you can simply run:
</p>

<pre class="language-bash"><code>$ tapestry init my-first-website</code></pre>

<p>
    Tapestry will create the folder <em>my-first-website</em> within the current working directory and scaffold into it
    the default project directory structure.
</p>

<p>
    The default project scaffold, for convenience comes with Laravel Elixir bundled in; before we continue you will need
    to run <code>npm install</code> to install it. For more information on the defined gulp tasks that come with Laravel
    Elixir, <a href="<?= $this->url('documentation/start-new-website') ?>/#defined-gulp-tasks">click here</a>.
</p>

<h4><a name="project-structure" href="#project-structure">Project Structure</a></h4>

<p>
    You should now within the <code>my-first-website</code> folder see the following generated file structure:
</p>

<pre class="language-treeview">
<code>my-first-website/
├── source/
|   ├── _assets/
|   |   ├── img
|   |   ├── js
|   |   └── less
|   ├── _blog/
|   |   └── 2016-01-01-hello-world.md
|   ├── _templates/
|   |   └── default.phtml
|   ├── _views/
|   |   └── blog.phtml
|   └── index.phtml
├── .gitignore
├── node_modules
├── config.php
├── gulpfile.js
├── kernel.php
└── package.json</code>
</pre>

<p>
    More details on the default Tapestry project structure can be found
    <a href="<?= $this->url('/documentation/start-new-website') ?>/#project-directory-structure">here</a>.
</p>

<p>
    Tapestry is &ldquo;<em>blog aware</em>&rdquo; out of the box so the majority of the default scaffold files are to
    do with displaying a collection of blog posts; you can find out more about creating your content
    <a href="<?= $this->url('documentation/your-content') ?>">here</a>.
</p>

<hr/>

<?php $this->insert('documentation/_partials/building-and-previewing') ?>