---
layout: documentation
title: Pretty URLS
---

<h2>Pretty URLS</h2>

<ul>
    <li><a href="#pretty-urls">Pretty URLS</a>
        <ul>
            <li><a href="#defining-custom-permalinks">Defining custom permalinks</a></li>
        </ul>
    </li>
</ul>

<h3><a name="pretty-urls" href="#pretty-urls">Pretty URLS</a></h3>

<p>
    <strong>@todo</strong> describe how the configuration setting for pretty urls works and explainm how that can be
    overloaded on a per file basis through front matter. In addition describe how to define custom permalinks and the
    basic template language that Tapestry uses for permalink generation.
</p>

<h4><a name="defining-custom-permalinks" href="#defining-custom-permalinks">Defining custom permalinks</a></h4>