---
layout: documentation
title: Taxonomy
---

<h2>Taxonomy</h2>

<ul>
    <li><a href="#taxonomy">Taxonomy</a>
        <ul>
            <li><a href="#defining-taxonomy-for-content-types">Defining Taxonomy for content types</a></li>
            <li><a href="#using-taxonomy-in-your-layouts">Using Taxonomy in your layouts</a></li>
        </ul>
    </li>
</ul>

<hr/>

<h3><a name="taxonomy" href="#taxonomy">Taxonomy</a></h3>
<p>&hellip;</p>
<h4><a name="defining-taxonomy-for-content-types" href="#defining-taxonomy-for-content-types">Defining Taxonomy for content types</a></h4>
<p>&hellip;</p>
<h4><a name="using-taxonomy-in-your-layouts" href="#using-taxonomy-in-your-layouts">Using Taxonomy in your layouts</a></h4>
<p>&hellip;</p>