<h3><a name="building-previewing" href="#building-previewing">Building &amp; Previewing</a></h3>

<p>
    To build your Tapestry website you execute the
    <a href="<?= $this->url('documentation/commands') ?>#build-command">build command</a> within the
    <code>my-first-website</code> folder:
</p>

<pre class="language-bash"><code>$ tapestry build</code></pre>

<p>
    This will build the files found in the <code>source</code> directory and output them to the <code>build_local</code>,
    local is the default environment for Tapestry and the build command accepts a <code>--env</code> argument with which
    you can define the environment, e.g the following will output to <code>build_development</code>:
</p>

<pre class="language-bash"><code>$ tapestry build --env=development</code></pre>

<h4><a name="preview-php" href="#preview-php">Previewing with PHP</a></h4>

<p>
    In the interest of keeping Tapestry light, previewing your website with PHP is handled directly by PHP itself, this
    is done via the following command:
</p>

<pre class="language-bash"><code>$ php -S 127.0.0.1:3000 -t build_local</code></pre>

<p>
    PHP will then serve up the static pages at <code>http://127.0.0.1:3000</code> while providing output akin to the
    below in to your console:
</p>

<pre class="language-bash"><code>PHP 5.6.24 Development Server started at Thu Mar 23 15:42:36 2017
Listening on http://127.0.0.1:3000
Document root is F:\build_local
Press Ctrl-C to quit.
[Thu Mar 23 15:42:41 2017] 127.0.0.1:53118 [200]: /
[Thu Mar 23 15:42:41 2017] 127.0.0.1:53119 [200]: /img/staticgen.gif
[Thu Mar 23 15:43:01 2017] 127.0.0.1:53145 [200]: /documentation
</code></pre>

<h4><a name="preview-gulp" href="#preview-gulp">Previewing with Gulp Task</a></h4>

<p>
    The default project scaffold comes with <a href="<?= $this->url('documentation/your-content') ?>">Laravel Elixir</a>,
    this provides out of the box tasks for less, imagemin, browserify and browserSync. Install via <code>npm install</code>
    and then <code>gulp watch</code> to preview your site.
</p>

<p>
    browserSync will open a new browser window/tab automatically and reload the page every time a change is noticed. I
    have noticed one distinct bug with the file watcher on Windows in that it will not notice if you add a new
    file to the watched path - in that case I personally execute <code>tapestry build</code> in a separate terminal.
</p>

<aside class="notice blue">
    <p>
        Now that you know how to build and preview your website,
        <a href="<?= $this->url('documentation/deploying') ?>">click here</a> to learn how to deploy.
    </p>
</aside>
