---
layout: default
title: Tapestry
description: Tapestry is a static site generator that uses the plates template system with front matter and markdown to make creating static sites quick to generate, simple to build and easy to extend.
---

<section class="my4 overflow-auto max-width-4 mx-auto px3">
    <header class="center my2">
        <h2>What is <span class="brand">Tapestry</span>?</h2>
    </header>
    <p class="large center px4">
        Tapestry is a static site generator that uses the <a href="http://platesphp.com/" target="_blank">plates template system</a> with front matter and markdown<br>
        to make creating static sites quick to generate, simple to build and easy to extend.
    </p>
</section>

<section class="mt4 dual-color">
    <div class="max-width-4 mx-auto">
        <div class="flex row-container" style="padding: 0 3rem;">
            <div class="col-6 pr4 light">
                <div class="code-container flex items-end">
                    <div class="code-box">
                        <pre class="language-php mono flex-none"><code><?= $this->codeExample('homepage-plates-example.php') ?></code></pre>
                    </div>
                </div>

                <h3 class="center">Use Plates, the native PHP template system <br>to build your static website.</h3>

                <p class="justify">
                    PHP Plates is a native PHP template system inspired by the excellent Twig template engine and is similarly fast, easy to use and easy to extend.
                </p>

                <p class="justify">
                    Tapestry has been kept intentionally basic, incorporating PHP Plates for templating remains true to that goal.
                </p>

            </div>

            <div class="col-6 pl4">
                <div class="code-container flex items-end">
                    <div class="code-box">
                        <pre class="language-yaml mono flex-none"><code><?= $this->codeExample('homepage-blog-example.php') ?></code></pre>
                    </div>
                </div>

                <h3 class="center" style="margin: 1.5em 0;">Markdown Extra, Taxonomy Support &amp; Frontmatter</h3>

                <p class="justify">
                    Markdown is an excellent format for writing, Tapestry extends upon that foundation by using Markdown Extra for formatting your content driven pages and Frontmatter for storing page meta, making Tapestry blog aware out of the box.
                </p>

                <p class="right h3">
                    <a href="<?= $this->url('documentation') ?>">Find out more in the documentation&hellip;</a>
                </p>

            </div>
        </div>
    </div>
</section>

<section class="red">
    <div class="max-width-4 mx-auto py4">
        <hr>
        <h2>Not <span>invented</span> here!</h2>
        <p class="large">
            <a href="https://www.staticgen.com/" target="_blank">StaticGen</a> has a list of other static site generators available, although to my knowledge<br>
            Tapestry is the only one to use the PHPPlates template engine.
        </p>
    </div>
</section>

<section class="my4 overflow-auto max-width-4 mx-auto px3">
    <header class="center my2">
        <h2>Fancy giving <span class="brand">Tapestry</span> a spin?</h2>
    </header>
    <p class="center px4">
        <a href="<?= $this->url('documentation') ?>" class="btn brand">Quickstart Guide</a>
    </p>
</section>
